---
alias: Update Configuration on Webhook
mode: single
id: update_configuration_on_webhook
trigger:
  - platform: webhook
    webhook_id: KwAR7V2aBqSzdLFr1yV2ztRuzbibNvtNaGNiYCPuvHcR
    allowed_methods:
      - POST
    local_only: true
action:
  - service: shell_command.update_config
  - service: homeassistant.reload_all
  - service: system_log.write
    data:
      level: info
      message: Home Assistant configuration updated via webhook
      logger: homeassistant.components.automation.update_config_on_webhook
